var questions = [
  {
    qprompt: "How many pokemon were in the first game?",
    c1: "A) 100",
    c2: "B) 151",
    c3: "C) 150",
    c4: "D) 101",
    answer: "B",
    answered: false,
  },
  {
    qprompt: "When was pokemon FIRST released?",
    c1: "A) 1996",
    c2: "B) 1997",
    c3: "C) 1998",
    c4: "D) 1999",
    answer: "A",
    answered: false,
  },
  {
    qprompt: "Can Pikachu learn Surf?",
    c1: "A) Yes",
    c2: "B) No",
    c3: "C) No but he can when he evolves",
    c4: "D) Yes but he can only use it in combat",
    answer: "B",
    answered: false,
  },
  {
    qprompt: "How can (specific) pokemon change gender?",
    c1: "A)Super Hidden Easter Eggs",
    c2: "B) Evolving",
    c3: "C) Trading",
    c4: "D) Never happens",
    answer: "B",
    answered: false,
  },
  {
    qprompt:
      "Which pokemon has the highest base stat total(Adding up all the stats from HP to Speed)?",
    c1: "A) Mega Rayquaza",
    c2: "B) Mega Mewtwo X",
    c3: "C) Mega Mewtwo Y",
    c4: "D) All of the above",
    answer: "D",
    answered: false,
  },
  {
    qprompt:
      "Which trait affects your pokemon's stats PERMANENTLY(Before Battle)?",
    c1: "A) Beauty",
    c2: "B) Abilities",
    c3: "C) Nature",
    c4: "D) No such trait",
    answer: "C",
    answered: false,
  },
  {
    qprompt: "What are IVs?",
    c1: "A) Injected Values", //what the police check for when they stop you
    c2: "B) Individual Values",
    c3: "C) Indeterminant Values",
    c4: "D) Don't Exist",
    answer: "B",
    answered: false,
  },
  {
    qprompt: "What are EVs?",
    c1: "A) Effort Values",
    c2: "B) Energy Values",
    c3: "C) Entertaining Values",
    c4: "D) 1999",
    answer: "A",
    answered: false,
  },
  {
    qprompt: "Who controls the pokemon ranking and tiers?",
    c1: "A) Nintendo",
    c2: "B) Game Freak",
    c3: "C) SMOGON",
    c4: "D) DOSUKE",
    answer: "C",
    answered: false,
  },
  {
    qprompt:
      "Which non-legendary pokemon got banned FIRST from OU, the most popular format?",
    c1: "A) Garchomp",
    c2: "B) Wobbuffet",
    c3: "C) Salamence",
    c4: "D) Kangaskhan",
    answer: "B",
    answered: false,
  },
  {
    qprompt:
      "Which pokemon FIRST OUTCLASSED its evolution(in terms of the tiers)?",
    c1: "A) Chansey",
    c2: "B) Porygon",
    c3: "C) Dusclops",
    c4: "D) None of the above",
    answer: "C",
    answered: false,
  },
  {
    qprompt: "What is the most controversial mechanic in Pokemon?", //This is kinda an opinion question
    c1: "A) Hazards(Stealth Rock)",
    c2: "B) Trapping(Shadow Tag and Arena Trap)",
    c3: "C) Switching",
    c4: "D) Pokemon is above controversy",
    answer: "B",
    answered: false,
  },
  {
    qprompt:
      "How many IVs can exist in a single stat?",
    c1: "23",
    c2: "31",
    c3: "256",
    c4: "510",
    answer: "B",
    answered: false,
  },
  {
    qprompt:
      "How many total EVs can you have on a pokemon?",
    c1: "23",
    c2: "31",
    c3: "256",
    c4: "510",
    answer: "D",
    answered: false,
  },
  {
    qprompt: "How many EVs can be used?",
    c1: "A) 307",
    c2: "B) 308",
    c3: "C) 309",
    c4: "D) 310",
    answer: "B",
    answered: false,
  },
  {
    qprompt: "Do DVs exist?",
    c1: "A) Yes",
    c2: "B) No",
    c3: "C) Yes but only in fan games",
    c4: "D) Yes but only in gen 3",
    answer: "A",
    answered: false,
  },
];
export { questions };
